name: data-leak-detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - streamlit
  - pandas
  - requests
  - beautifulsoup4
  - pyopenssl
  - geoip2
  - pip
  - pip:
    - python-whois
    - fpdf
    - python-nmap