name: data_leak_detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - streamlit
  - pandas
  - requests
  - beautifulsoup4
  - lxml
  - html5lib
  - urllib3
  - pyOpenSSL
  - pip:
    - python-whois
    - streamlit-extras