name: data-leak-detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - streamlit
  - pandas
  - requests
  - beautifulsoup4
  - python-whois
  - pyopenssl
  - geoip2
  - sqlite
  - folium
  - pip
  - pip:
    - fpdf
    - python-nmap
    - streamlit-folium
    - ipinfo==3.0.0