name: scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - streamlit
    - streamlit_extras
    - pandas
    - requests
    - beautifulsoup4
    - lxml
    - html5lib