name: data-leak-detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - streamlit
  - pandas
  - requests
  - beautifulsoup4
  - python-whois
  - pyopenssl
  - geoip2
  - fpdf
  - python-nmap
  - ipinfo=3.0.0
  - ipaddress
  - pydeck
  - pip
  - pip:
    - streamlit-option-menu