name: data-leak-detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - streamlit
  - pandas
  - requests
  - beautifulsoup4
  - python-whois
  - pyopenssl
  - geoip2
  - fpdf
  - ipinfo=3.0.0
  - safety
  - pydeck
  - IPy  # Add this line
  - pip
  - pip:
    - streamlit-option-menu