name: scraper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - streamlit
  - pandas
  - requests
  - beautifulsoup4
  - lxml
  - html5lib
  - urllib3
  - whois
  - pyOpenSSL
  - pip:
    - streamlit_extras
    - python-whois